### ISSUE TITLE
Implement example and test for Galene

### ISSUE THREAD

**Issue by eljamm** [ngi-nix/ngipkgs#712]
## Instrucitons

Given that the [project has been added to projects/Galene](https://github.com/ngi-nix/ngipkgs/issues/711), add a basic example and [NixOS VM test](https://nix.dev/tutorials/nixos/integration-testing-using-virtual-machines.html) that showcase how to configure and use it.

**Comment by Ellipse0934** [comment]
Hi, I'd like to take this on.

**Comment by eljamm** [comment]
How is this going for you @Ellipse0934? Need help with anything?

**Comment by Garvit-77** [comment]
Hey @eljamm I would like to take on the issue

**Comment by Garvit-77** [comment]
Hey @fricklerhandwerk , @eljamm 
I was reviewing the mentioned PRs which depicts that the issue is already resolved 
or can you please guide me if I'm wrong .

**Comment by eljamm** [comment]
Well, the example added in that PR is really basic (we can change the port and add certs)  and the test doesn't do anything, currently, so we don't know if the example even works. As such, this issue remains unsolved since what we currently have doesn't "showcase how to configure and use [Galene]" as per the task's requirements.

**Comment by Garvit-77** [comment]
@eljamm thank you for that information , I will improvise example and adding tests to it

My background:
I have been contributing to CNCF projects earlier and 
I'm a newbie(parsing Docs for better understanding) to nix as I just came across the Summer of Nix 2025 program!
